baseurl = "https://ltgouvea.github.io/"
languageCode = "pt-br"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "pink"
  showMenuItems = 3

  [languages.en]
    title = "Lucas Gouvêa"
    subtitle = "FullStack Dev"
    keywords = "Fullstack, Javascript, PHP, Developer, Github"
    copyright = "2019"
    menuMore = "Mostrar Mais"
    readMore = "Ler mais"
    readOtherPosts = "Ler outros posts"

    [languages.en.params.logo]
      logoText = "K2 ># "
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "curriculum"
        name = "Currículo"
        url = "/curriculum"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projetos"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "contato"
        name = "Contato"
        url = "/contato"
