baseurl = "https://ltgouvea.github.io/"
languageCode = "pt-br"
theme = "terminal"
paginate = 5

[markup.goldmark.renderer]
unsafe= true

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 3

  [languages.en]
    title = "Lucas Gouvêa - Web Developer"
    subtitle = "Brasil"
    keywords = "Developer, Web Developer, PHP, Fullstack, Javascript, Github"
    copyright = "2020"
    menuMore = "Mostrar Mais"
    readMore = "Ler mais"
    readOtherPosts = "Ler outros posts"

    [languages.en.params.logo]
      logoText = "K2 ># "
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "curriculum"
        name = "Currículo"
        url = "/curriculum"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projetos"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "contato"
        name = "Contato"
        url = "/contato"
